spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pcams?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lm18252901109
  jpa:
    show-sql: false
    generate-ddl: true
    database: mysql
  mail:
    username: ulyssesk@foxmail.com
    password: rfbwwfeavsxtjdbg
    host: smtp.qq.com
    port: 465
    properties:
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: ture
      mail.smtp.ssl.required: true

server:
  servlet:
    context-path:
  port: 8430

erupt-app:
  # 是否加密
  pwd-transfer-encrypt: false

erupt:
  upms:
    # 登陆session
    expire-time-by-login: 300

